### ISSUE TITLE
Error Intentar Crear User

### ISSUE THREAD

**Issue by tjaoc** [soker90/arroyo-erp-api#130]
Despues intentar hacer de mil formas diferentes me salta siempre Error - [Error] - jwt malformed y no soy capaz de crear el usuario, entrar en la App ni nada. Puedes verificar por favor

**Comment by soker90** [comment]
@tjaoc el usuario se crea usando un endpoint, pero es necesario ser usuario administrador. Lo que hago es crearlo directamente en la BBDD porque no es algo que necesite hacer normalmente. Perdona no haber contestado antes, imagino que ya no te hará falta la ayuda.
